apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dummysites.example.com
spec:
  group: example.com
  scope: Namespaced
  names:
    kind: DummySite
    plural: dummysites
    singular: dummysite
    shortNames:
    - ds
  versions:
  - name: v1
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            required:
            - website_url
            properties:
              website_url:
                type: string
                format: uri
          status:
            type: object
            properties:
              ready:
                type: boolean
              url:
                type: string
    additionalPrinterColumns:
    - name: Website URL
      type: string
      description: The URL to fetch HTML from
      jsonPath: .spec.website_url
    - name: Ready
      type: boolean
      description: Whether the site is ready
      jsonPath: .status.ready
    - name: Service URL
      type: string
      description: The service URL to access the site
      jsonPath: .status.url