apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: log-output-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/mmucahitOt/KubernetesExercises.git
    targetRevision: main
    path: log_output/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: exercises
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true

