apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong-deployment
  template:
    metadata:
      labels:
        app: ping-pong-deployment
    spec:
      containers:
        - name: ping-pong-container
          image: ${DOCKER_REGISTRY}/ping_pong:latest
          env:
            - name: PING_PONG_PORT
              value: "${PING_PONG_PORT}"
            - name: PORT
              value: "${PING_PONG_PORT}"
          ports:
            - name: http-pingpong
              containerPort: ${PING_PONG_PORT}
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"  