apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ping-pong-claim
spec:
  storageClassName: my-persistent-volume-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi