apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistent-volume-pv
spec:
  storageClassName: my-persistent-volume-pv
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  local:
    path: /tmp/kube
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k3d-k3s-default-agent-0