apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-app-claim
  namespace: project
spec:
  storageClassName: todo-app-volume-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi