apiVersion: v1
kind: Service
metadata:
  name: todo-app-deployment-svc
  namespace: project
spec:
  type: ClusterIP
  selector:
    app: todo-app-deployment 
  ports:
    - port: 2345
      protocol: TCP
      targetPort: ${TODO_APP_PORT}